name: "Dep job Example"

on:
  push:
    branches:
      - main

jobs:
  job1:
    runs-on: ubuntu-latest
    steps:
      - name: "step B"
        run: echo "hello job B"

  job2:
    runs-on: ubuntu-latest
    needs: job1
    steps:
      - name: "step A"
        run: echo "hello job2"
