name: "Expression function"

on:
  push:
    branches:
      - main

jobs:
  Expression_functions:
    runs-on: ubuntu-latest
    steps:
      - name: Check if string contains substrings
        if: ${{ contains('Hello world', 'ello') }}
        run: echo "The string contains substrings"

      - name: Check if string ends with
        if: ${{ endsWith('helloworld', 'ld') }}
        run: echo "String ends with ld"

      - name: Format and echo string
        run: echo "${{ format('Hello {0} {1} {2}', 'mona', 'the', 'octate') }}"

      - name: Join issue labels (example fallback)
        if: ${{ github.event_name == 'issues' }}
        run: echo "Issue labels join logic would go here."

      - name: Convert job context to JSON
        run: echo "from json ${{ fromJSON('{"hello":"world"}").hello }}"

      - name: Hash files
        run: echo "Hash of files: ${{ hashFiles('package-lock.json', 'Gemfile.lock') }}"

      - name: The job has succeeded
        if: ${{ success() }}
        run: echo "The job has
