name: Schedule work to trigger every minute

on:
  schedule:
    - cron: '*/1 * * * *'  # Triggers every minute

jobs:
  hello_world:
    runs-on: ubuntu-latest
    steps:
      - name: Echo current time
        run: |
          echo "The current server time is:"
          date
