name: Windows Runner

on:
  push:
    branches:
      - main

jobs:
  build-and-test:
    runs-on: windows-latest
    steps:
      - name: Check out code
        uses: actions/checkout@v3

      - name: Install .NET SDK
        run: choco install dotnetcore-sdk
        shell: powershell

      - name: Compile and run C# code
        run: |
          Add-Content -Path "hello.cs" -Value @"
          using System;

          public class Hello
          {
              public static void Main()
              {
                  Console.WriteLine("Hello, world!");
              }
          }
          "@

          dotnet new console --force --no-restore
          Move-Item -Path "hello.cs" -Destination "Program.cs" -Force
          dotnet run
        shell: powershell
